### ISSUE TITLE
Use with Firebase Functions

### ISSUE THREAD

**Issue by Turkm** [nodertc/stun#16]
Hi Dmitriy, you are doing really great job

I was wondering how to add this package to firebase functions, because i want to implement STUN functionality inside firebase, so can this package achieve that or is it beyond it's limitation.

**Comment by reklatsmasters** [comment]
Thanks, @Turkm!

I've never used Firebase Functions. The [documentation](https://firebase.google.com/docs/functions/) says that Firebase Functions works over https protocol, but STUN required UDP.

**Comment by Turkm** [comment]
that's will make it impossible then, thanks again Dmitriy and keep the good work.
